"""Materialize one frozen I5 §10 lifecycle step into a scratch workdir (I5 Slice 4).

    uv run python mutate.py <target> <step> <workdir> [--inventory <Q-INV output>]

The frozen dossier declarations are copied, never modified, and only the edits the scenario file
names are applied to the copy:
- omit X, and drop X's entry from the identity-bindings copy;
- add an unbound copy of one declaration;
- inject a disagreeing root `x-aip-service-id` into X's copy;
- move the copy to another root;
- add a tombstone for X.

The workdir's *contents* are replaced, but the directory itself is kept, because it is
bind-mounted into the lifecycle AIP container (docker-compose.lifecycle.yml). The script prints the
digest of what it wrote.
"""

import argparse
import csv
import hashlib
import shutil
import sys
from pathlib import Path

import yaml

LIFECYCLE_DIR = Path(__file__).resolve().parent
# The source ids come from AIP's own algorithm, never a copy of it. So the repository root (this
# file is docs/real-world-validation/v0.5.0/lifecycle/mutate.py) must be importable.
sys.path.insert(0, str(LIFECYCLE_DIR.parents[3]))

from app.sources.identity import source_instance_id
from app.sources.model import SourceKind

BINDINGS = "bindings/architecture-identity-bindings.yaml"
CONTAINER_PREFIX = "lifecycle"  # the workdir is mounted at /app/lifecycle; AIP's cwd is /app
TOMBSTONES = "tombstones.yaml"


def load_scenario(target: str) -> dict:
    return yaml.safe_load((LIFECYCLE_DIR / "scenarios" / f"{target}.yaml").read_text())


def step_of(scenario: dict, step_id: str) -> dict:
    (step,) = [s for s in scenario["steps"] if s["id"] == step_id]
    return step


def x_source_instance_id(scenario: dict) -> str:
    return str(
        source_instance_id(
            configured_source_id=scenario["declarations_source_id"],
            source_kind=SourceKind.FILESYSTEM,
            normalized_root_document_path=scenario["x"],
        )
    )


def clear(workdir: Path) -> None:
    for child in workdir.iterdir():
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()


def inject_service_id(path: Path, service_id: str) -> None:
    lines = path.read_text().split("\n")
    (index,) = [i for i, line in enumerate(lines) if line == "info:"]
    lines.insert(index, f"x-aip-service-id: {service_id}")
    path.write_text("\n".join(lines))


def drop_binding(bindings_path: Path, sid: str) -> None:
    document = yaml.safe_load(bindings_path.read_text())
    before = len(document["bindings"])
    document["bindings"] = [b for b in document["bindings"] if b["sourceInstanceId"] != sid]
    if len(document["bindings"]) != before - 1:
        raise SystemExit("expected exactly one binding for X")
    document["metadata"]["revision"] = f"{document['metadata']['revision']}-without-x"
    bindings_path.write_text(
        "# Lifecycle copy (I5 §10), generated by mutate.py: X's binding is dropped.\n"
        + yaml.safe_dump(document, sort_keys=False, allow_unicode=True)
    )


def config_text(scenario: dict, step: dict) -> str:
    sources: dict = {
        "directories": [
            {"id": scenario["declarations_source_id"], "root": f"{CONTAINER_PREFIX}/{step['root']}"}
        ]
    }
    if step.get("tombstone_x"):
        sources["tombstones"] = [f"{CONTAINER_PREFIX}/{TOMBSTONES}"]
    config = {
        "architecture_intelligence": {
            "sources": sources,
            "graph": {"uri": "bolt://localhost:7687", "database": "neo4j"},
            "import": {"openapi": True, "asyncapi": True, "architecture_manifest": True},
            "llm": {"enabled": False},
            "runtime_analysis": {"default_environment": f"{scenario['target']}-i5-lifecycle"},
        }
    }
    return (
        f"# Lifecycle AIP config for {scenario['target']}, generated by mutate.py (I5 §10).\n"
        + yaml.safe_dump(config, sort_keys=False, allow_unicode=True)
    )


def read_inventory(path: Path) -> dict:
    """Parses the frozen Q-INV query's `cypher-shell --format plain` output (a header plus one row)."""
    rows = list(csv.reader(path.read_text().strip().splitlines(), skipinitialspace=True))
    if len(rows) != 2:
        raise SystemExit("Q-INV must return exactly one CurrentInventory row")
    header = [h.split(".", 1)[-1] for h in rows[0]]
    return dict(zip(header, rows[1], strict=True))


def write_tombstone(scenario: dict, workdir: Path, inventory_path: Path | None) -> None:
    if inventory_path is None:
        raise SystemExit("a tombstone step needs --inventory <Q-INV output taken after L5>")
    inventory = read_inventory(inventory_path)
    template = yaml.safe_load((LIFECYCLE_DIR / "tombstone.template.yaml").read_text())
    tombstone = {
        "target_source_instance_id": x_source_instance_id(scenario),
        "discovery_scope_id": inventory["discovery_scope_id"],
        "expected_prior_inventory_revision": inventory["inventory_revision"],
        "scope_definition_digest": inventory["scope_definition_digest"],
        **template,
    }
    (workdir / TOMBSTONES).write_text(
        yaml.safe_dump({"tombstones": [tombstone]}, sort_keys=False, allow_unicode=True)
    )


def materialize(target: str, step_id: str, workdir: Path, inventory: Path | None = None) -> None:
    scenario = load_scenario(target)
    step = step_of(scenario, step_id)
    frozen = (LIFECYCLE_DIR / scenario["dossier_declarations"]).resolve()
    if frozen in workdir.resolve().parents or workdir.resolve() == frozen:
        raise SystemExit("the workdir must not be inside the frozen dossier")
    clear(workdir)
    if step.get("materialize", True):
        root = workdir / step["root"]
        shutil.copytree(frozen, root)
        x_path = root / scenario["x"]
        if step.get("omit_x"):
            x_path.unlink()
            drop_binding(root / BINDINGS, x_source_instance_id(scenario))
        if "inject_x_service_id" in step:
            inject_service_id(x_path, step["inject_x_service_id"])
        if "unbound_copy" in step:
            destination = root / step["unbound_copy"]["to"]
            destination.parent.mkdir(parents=True)
            shutil.copyfile(frozen / step["unbound_copy"]["from"], destination)
    (workdir / "config.yaml").write_text(config_text(scenario, step))
    if step.get("tombstone_x"):
        write_tombstone(scenario, workdir, inventory)


def tree_digest(workdir: Path, *, exclude: frozenset[str] = frozenset({TOMBSTONES})) -> str:
    """sha256 over the sorted `relative-path NUL sha256(bytes)` lines of every file in the tree,
    ignoring `__pycache__`."""
    lines = [
        f"{path.relative_to(workdir).as_posix()}\0{hashlib.sha256(path.read_bytes()).hexdigest()}"
        for path in sorted(workdir.rglob("*"))
        if path.is_file()
        and "__pycache__" not in path.parts
        and path.relative_to(workdir).as_posix() not in exclude
    ]
    return hashlib.sha256("\n".join(lines).encode()).hexdigest()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("target")
    parser.add_argument("step")
    parser.add_argument("workdir", type=Path)
    parser.add_argument("--inventory", type=Path)
    args = parser.parse_args(argv)
    if not args.workdir.is_dir():
        raise SystemExit("the workdir must be an existing directory (it is bind-mounted)")
    materialize(args.target, args.step, args.workdir, args.inventory)
    print(tree_digest(args.workdir))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
